---
 - fields:
    headline: 'Interview: Carlos Richardson''s Mt. Kilimanjaro adventure'
    subHeadline: The fearless explorer tells all about his volcanic climb
    imageUrl: https://dl.airtable.com/.attachments/6be902074d1b866444e3a3cbd08beda9/0fe5e344/kilimanjaro-1203937_1280.jpg
 - fields:
    headline: Summer-inspired bites with Sandra Key
    subHeadline: Refreshing and delicious recipes from celebrated chef Sandra Key
 - fields:
    headline: Fly to the Cayman Islands
    subHeadline: What to do, eat, and see on your next visit to the Cayman Islands
    imageUrl: https://dl.airtable.com/qQCqvYGUSUNcqQouwowo_pexels-photo-248797.jpeg%3Fh%3D350%26auto%3Dcompress%26cs%3Dtinysrgb
 - fields:
    headline: 11 summer inspired beach looks under $100
    subHeadline: Step into summer while staying on budget
    imageUrl: https://dl.airtable.com/WzF1oIqjTSu9QW837gjp_pexels-photo-390625.jpeg%3Fh%3D350%26auto%3Dcompress%26cs%3Dtinysrgb
 - fields:
    headline: Diggin' the Maldives
    subHeadline: 'The ultimate guide for a jaw-dropping journey to the coral islands '
    imageUrl: https://dl.airtable.com/jnSFZNjrQEC6jVvDRWSW_pexels-photo-221455.jpeg%3Fh%3D350%26auto%3Dcompress%26cs%3Dtinysrgb
 - fields:
    headline: Poolside views
    imageUrl: https://dl.airtable.com/pQXlwEtaSu8uo9dYZKvQ_pexels-photo-261102.jpeg%3Fh%3D350%26auto%3Dcompress%26cs%3Dtinysrgb
 - fields:
    headline: Must-see museums
    subHeadline: The most extraordinary museums in the world
    imageUrl: https://dl.airtable.com/.attachments/92c8337804fe0c2fb9d61076844a0721/724ac19e/architecture-art-arts-1839919.jpg
 - fields:
    headline: Spotlight on Jacques Martin
    subHeadline: The legendary chef dishes on his international culinary inspirations
    imageUrl: https://dl.airtable.com/XvQ4Cr9JQdOyBmY1IFF1_pexels-photo-196410.jpeg%3Fw%3D940%26h%3D650%26auto%3Dcompress%26cs%3Dtinysrgb
 - fields:
    headline: 'Creative conversations: An interview with Tokyo''s fashion designers'
 - fields:
    headline: 10 tips for making the most of your Mexico cruise
 - fields:
    headline: Voyager's favorite 5-star hotels
    subHeadline: Our hotel picks that we think you'll love, too
    imageUrl: https://dl.airtable.com/RgTWUUeSSm4qiGebiGEA_pexels-photo-205342.jpeg%3Fw%3D940%26h%3D650%26auto%3Dcompress%26cs%3Dtinysrgb
 - fields:
    headline: The cozy countryside is Britain at its best
 - fields:
    headline: 5 of the most affordable safaris
    subHeadline: Get deep into the desert without deep pockets
    imageUrl: https://dl.airtable.com/BwEXXvR5QdKIldt4Vkmw_pexels-photo-247376.jpeg%3Fh%3D350%26auto%3Dcompress%26cs%3Dtinysrgb
 - fields:
    headline: Is a luxury stay worth it?
    subHeadline: Travel experts weigh in on the true cost of amenities
    imageUrl: https://dl.airtable.com/SJnOuNdSuqiWwyyHAC6A_pexels-photo-189296.jpeg%3Fh%3D350%26auto%3Dcompress%26cs%3Dtinysrgb